const BIENS_CATALOGUE = [
  {
    id: 'bien_001',
    titre: 'Appartement T2 — Toulouse Capitole',
    ville: 'Toulouse',
    surface: 42,
    pieces: 2,
    prix: 189000,
    loyer_estime: 750,
    rendement: 5.8,
    dispositif: 'Jeanbrun Social',
    mensualite: 820,
    effort_reel: 248,
    etage: '3ème sur 5',
    dpe: 'B',
    disponible: true,
    lat: 43.6047, lon: 1.4442,
    promoteur: 'Nexity',
    livraison: 'T3 2026',
    tags: ['Investissement', 'Jeanbrun', 'Centre-ville']
  },
  {
    id: 'bien_002',
    titre: 'Studio meublé — Lyon Part-Dieu',
    ville: 'Lyon',
    surface: 28,
    pieces: 1,
    prix: 145000,
    loyer_estime: 620,
    rendement: 6.1,
    dispositif: 'LMNP',
    mensualite: 630,
    effort_reel: 180,
    etage: '5ème sur 8',
    dpe: 'C',
    disponible: true,
    lat: 45.7600, lon: 4.8590,
    promoteur: 'Bouygues Immobilier',
    livraison: 'T2 2026',
    tags: ['LMNP', 'Meublé', 'Rentabilité']
  },
  {
    id: 'bien_003',
    titre: 'T3 familial — Bordeaux Chartrons',
    ville: 'Bordeaux',
    surface: 68,
    pieces: 3,
    prix: 312000,
    loyer_estime: 1100,
    rendement: 4.9,
    dispositif: 'Résidence principale',
    mensualite: 1380,
    effort_reel: 1380,
    etage: '2ème sur 4',
    dpe: 'A',
    disponible: true,
    lat: 44.8560, lon: -0.5710,
    promoteur: 'Vinci Immobilier',
    livraison: 'T4 2026',
    tags: ['Résidence principale', 'Famille', 'Quartier prisé']
  },
  {
    id: 'bien_004',
    titre: 'T2 neuf — Montpellier Antigone',
    ville: 'Montpellier',
    surface: 45,
    pieces: 2,
    prix: 198000,
    loyer_estime: 780,
    rendement: 5.6,
    dispositif: 'Jeanbrun Social',
    mensualite: 860,
    effort_reel: 290,
    etage: '4ème sur 6',
    dpe: 'A',
    disponible: true,
    lat: 43.6100, lon: 3.8900,
    promoteur: 'Icade',
    livraison: 'T1 2027',
    tags: ['Neuf', 'Jeanbrun', 'Université']
  },
  {
    id: 'bien_005',
    titre: 'Studio — Nantes Centre',
    ville: 'Nantes',
    surface: 25,
    pieces: 1,
    prix: 125000,
    loyer_estime: 550,
    rendement: 6.4,
    dispositif: 'LMNP',
    mensualite: 540,
    effort_reel: 155,
    etage: '1er sur 3',
    dpe: 'C',
    disponible: false,
    lat: 47.2173, lon: -1.5534,
    promoteur: 'Cogedim',
    livraison: 'Livré',
    tags: ['LMNP', 'Étudiant', 'Centre-ville']
  },
  {
    id: 'bien_006',
    titre: 'T4 standing — Paris 11ème',
    ville: 'Paris',
    surface: 85,
    pieces: 4,
    prix: 890000,
    loyer_estime: 2800,
    rendement: 3.8,
    dispositif: 'Déficit foncier',
    mensualite: 3900,
    effort_reel: 1500,
    etage: '6ème sur 7',
    dpe: 'D',
    disponible: true,
    lat: 48.8590, lon: 2.3800,
    promoteur: 'Kaufman & Broad',
    livraison: 'T2 2026',
    tags: ['Paris', 'Déficit foncier', 'Standing']
  },
  {
    id: 'bien_007',
    titre: 'T2 neuf — Rennes Beaulieu',
    ville: 'Rennes',
    surface: 40,
    pieces: 2,
    prix: 175000,
    loyer_estime: 680,
    rendement: 5.5,
    dispositif: 'Jeanbrun Social',
    mensualite: 760,
    effort_reel: 220,
    etage: '2ème sur 5',
    dpe: 'A',
    disponible: true,
    lat: 48.1120, lon: -1.6380,
    promoteur: 'Eiffage Immobilier',
    livraison: 'T3 2026',
    tags: ['Neuf', 'Jeanbrun', 'Campus']
  },
  {
    id: 'bien_008',
    titre: 'T3 Denormandie — Marseille Joliette',
    ville: 'Marseille',
    surface: 62,
    pieces: 3,
    prix: 220000,
    loyer_estime: 900,
    rendement: 5.9,
    dispositif: 'Denormandie',
    mensualite: 960,
    effort_reel: 280,
    etage: '3ème sur 6',
    dpe: 'C',
    disponible: true,
    lat: 43.3060, lon: 5.3660,
    promoteur: 'Rénovation privée',
    livraison: 'T1 2027',
    tags: ['Ancien rénové', 'Denormandie', 'Port']
  },
  {
    id: 'bien_009',
    titre: 'Studio meublé — Lille Wazemmes',
    ville: 'Lille',
    surface: 22,
    pieces: 1,
    prix: 112000,
    loyer_estime: 520,
    rendement: 6.7,
    dispositif: 'LMNP',
    mensualite: 485,
    effort_reel: 130,
    etage: '4ème sur 5',
    dpe: 'B',
    disponible: true,
    lat: 50.6270, lon: 3.0480,
    promoteur: 'Nacarat',
    livraison: 'Livré',
    tags: ['LMNP', 'Meublé', 'Étudiant']
  },
  {
    id: 'bien_010',
    titre: 'T2 neuf — Strasbourg Neudorf',
    ville: 'Strasbourg',
    surface: 44,
    pieces: 2,
    prix: 205000,
    loyer_estime: 790,
    rendement: 5.4,
    dispositif: 'Jeanbrun Social',
    mensualite: 890,
    effort_reel: 300,
    etage: '1er sur 4',
    dpe: 'A',
    disponible: true,
    lat: 48.5700, lon: 7.7700,
    promoteur: 'Stradim',
    livraison: 'T4 2026',
    tags: ['Neuf', 'Jeanbrun', 'Tram']
  },
  {
    id: 'bien_011',
    titre: 'T3 résidence seniors — Nice Cimiez',
    ville: 'Nice',
    surface: 58,
    pieces: 3,
    prix: 285000,
    loyer_estime: 1050,
    rendement: 5.2,
    dispositif: 'LMNP',
    mensualite: 1240,
    effort_reel: 380,
    etage: '2ème sur 5',
    dpe: 'B',
    disponible: true,
    lat: 43.7150, lon: 7.2720,
    promoteur: 'Domitys',
    livraison: 'T2 2027',
    tags: ['LMNP', 'Seniors', 'Côte d\'Azur']
  },
  {
    id: 'bien_012',
    titre: 'T2 — Villeurbanne Campus',
    ville: 'Villeurbanne',
    surface: 38,
    pieces: 2,
    prix: 168000,
    loyer_estime: 660,
    rendement: 5.7,
    dispositif: 'Jeanbrun Social',
    mensualite: 730,
    effort_reel: 210,
    etage: '3ème sur 7',
    dpe: 'A',
    disponible: true,
    lat: 45.7680, lon: 4.8800,
    promoteur: 'Nexity',
    livraison: 'T3 2026',
    tags: ['Neuf', 'Jeanbrun', 'Campus']
  }
];

export async function onRequestGet({ request }) {
  const url = new URL(request.url);
  const ville = url.searchParams.get('ville');
  const dispositif = url.searchParams.get('dispositif');
  const prix_max = url.searchParams.get('prix_max');

  let biens = [...BIENS_CATALOGUE];

  if (ville) biens = biens.filter(b => b.ville.toLowerCase() === ville.toLowerCase());
  if (dispositif) biens = biens.filter(b => b.dispositif.toLowerCase().includes(dispositif.toLowerCase()));
  if (prix_max) biens = biens.filter(b => b.prix <= parseFloat(prix_max));

  return new Response(JSON.stringify({
    success: true,
    total: biens.length,
    biens
  }), {
    headers: {
      'Content-Type': 'application/json',
      'Access-Control-Allow-Origin': '*'
    }
  });
}
